"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	async up(queryInterface, Sequelize) {
		return queryInterface.bulkInsert("Actions", [
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-01T12:00:00",
				end_time: "2024-01-01T17:00:00",
				is_group: 1,
				name: "Park BBQ",
				description:
					"Join us for a sizzling day of flavor and fun at our BBQ in the Park event! Picture a sun-drenched day filled with the mouthwatering aroma of grilled delights wafting through the air. Bring your friends and family to indulge in a feast of smoky barbecue favorites, from perfectly grilled burgers and hot dogs to tender ribs and savory skewers. The park transforms into a lively hub of laughter, games, and good times. Enjoy the laid-back atmosphere as you lounge on picnic blankets, savoring delicious bites and refreshing drinks. With live music, friendly faces, and the great outdoors as your backdrop, our BBQ in the Park promises a perfect blend of relaxation and gastronomic delight. Come join the festivities and make lasting memories in the heart of nature!",

				organiserId: 2,
				online_link: null,
				latitude: 41.399547,
				longitude: 2.170496,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 1,
				start_time: "2024-01-05T20:00:00",
				end_time: "2024-01-05T23:30:00",
				is_group: 1,
				name: "Movie Night",
				description:
					"Experience the warmth and inspiration of a heartfelt movie night with 'Pride.' This cinematic gem invites you on a captivating journey, exploring the triumphs and challenges of a diverse group coming together for a common cause. As the characters navigate through the intricacies of unity, acceptance, and the pursuit of equality, 'Pride' weaves a powerful narrative that transcends boundaries. Join us for an evening of laughter, tears, and a celebration of love and solidarity as we immerse ourselves in the beauty of 'Pride,' a film that not only entertains but leaves an indelible mark on the heart.",
				organiserId: 2,
				online_link: " https://zoom.us/j/5551112222",
				latitude: 41.401559,
				longitude: 2.17056,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 0,
				start_time: null,
				end_time: null,
				is_group: 0,
				name: "Article Reading",
				description:
					"Embark on a journey of insight and discovery as you dive into an enriching article about the acclaimed film 'Pride.' This compelling piece unravels the layers of the movie, offering a thoughtful exploration of its themes, characters, and the profound impact it has left on audiences. Immerse yourself in the analysis, gaining a deeper understanding of the film's narrative nuances, social relevance, and the powerful emotions it elicits. Delve into interviews with the cast and creators, uncovering the behind-the-scenes magic that brought this cinematic gem to life. Whether you're a film enthusiast or simply intrigued by powerful storytelling, reading this article is a gateway to appreciating the artistry and cultural significance of 'Pride.' Join us on this intellectual journey as we celebrate the beauty of storytelling and the profound messages embedded in this remarkable film.",

				organiserId: 1,
				online_link:
					"https://www.theguardian.com/film/2014/aug/31/pride-film-gay-activists-miners-strike-interview",
				latitude: 41.401173,
				longitude: 2.172362,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: null,
				end_time: null,
				is_group: 0,
				name: "Buy a book!",
				description:
					"Step into a world of literary diversity and support a vibrant community by purchasing a book from our local LGBTQ bookstore. As you browse the shelves, each book becomes a doorway to unique narratives, diverse voices, and untold stories that celebrate the richness of the LGBTQ experience. Your purchase not only adds a new gem to your personal library but also contributes directly to fostering inclusivity and empowering a local business that champions diversity. Join us in promoting a love for literature and supporting our LGBTQ community as we cherish the joy of discovery, one book at a time. Your choice makes a difference, creating a more inclusive and welcoming space for everyone in our shared literary journey.",

				organiserId: 1,
				online_link: null,
				latitude: 41.403217,
				longitude: 2.17056,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-06T18:00:00",
				end_time: "2024-01-06T20:30:00",
				is_group: 1,
				name: "Speed Dating",
				description:
					"Embark on a thrilling journey of connection and possibility with our speed dating event! Imagine a vibrant atmosphere filled with laughter, anticipation, and the promise of exciting encounters. Whether you're seeking romance or simply eager to expand your social circle, speed dating offers a dynamic and efficient way to meet like-minded individuals. Engage in a series of brief, meaningful conversations, each lasting just long enough to make a memorable impression. With a timer ticking, discover the chemistry that sparks genuine connections and opens the door to potential relationships. Join us for an evening of spontaneity and discovery, where every conversation is a chance to find a new connection and perhaps even a spark that lasts a lifetime. Get ready to embrace the thrill of meeting new faces and exploring the endless possibilities that speed dating brings to the world of relationships.",
				organiserId: 2,
				online_link: null,
				latitude: 41.402914,
				longitude: 2.17466,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Park Walk",
				description:
					"Escape the hustle and bustle of daily life with a leisurely park walk that promises a breath of fresh air and a rejuvenating experience. As you enter the green oasis, the rhythmic rustle of leaves overhead and the gentle melodies of nature surround you. Meander along winding paths, each turn revealing picturesque scenes of blooming flowers, towering trees, and tranquil ponds. Embrace the serenity as you stroll under the canopy of branches, sunlight filtering through the leaves. Take a moment to pause at scenic viewpoints, allowing the beauty of your surroundings to sink in. Whether you're seeking solitude for introspection or sharing the joy with companions, a park walk is an opportunity to connect with nature, clear your mind, and find solace in the simple yet profound wonders of the outdoors.",
				organiserId: 2,
				online_link: null,
				latitude: 41.403243,
				longitude: 2.168971,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Debate on Neo-Fascism",
				description:
					"Engage in a thought-provoking and challenging exploration of political ideologies with a neo-fascism debate. This discourse invites participants to critically examine the principles and tenets associated with neo-fascist thought. Delve into the complexities of historical context, social implications, and the contemporary resonance of these ideologies. As participants present and counter arguments, the debate fosters an environment for rigorous intellectual exchange, aiming to deepen understanding and provoke critical thinking. While discussions on such topics can be intense, the goal is to provide a platform for examining contrasting viewpoints within the bounds of respectful discourse. Join us for an enlightening and intellectually stimulating neo-fascism debate that encourages reflection and promotes a nuanced understanding of political ideologies in today's world.",
				organiserId: 2,
				online_link: null,
				latitude: 41.572815,
				longitude: 2.016293,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Book Club",
				description:
					"Step into a vibrant world of literature and lively discourse with our LGBTQ Book Club and Debate. Immerse yourself in a diverse selection of books that beautifully capture the LGBTQ experience, exploring themes of love, identity, and resilience. Engage in thought-provoking discussions that celebrate the rich tapestry of LGBTQ narratives, fostering a sense of community and understanding. Our book club not only provides a space for shared literary exploration but also encourages spirited debates that delve into the complexities of the stories we read. Join us in creating an inclusive and supportive environment where diverse voices are heard, stories are cherished, and where every meeting is an opportunity to learn, connect, and celebrate the vibrant LGBTQ literary landscape.",

				organiserId: 2,
				online_link: null,
				latitude: 41.572815,
				longitude: 2.016293,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},

			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Salsa Night",
				description:
					"Dive into the rhythm of diversity and inclusion with our LGBTQ Salsa Dancing Night. Join a community that celebrates the freedom of self-expression through the lively and passionate beats of salsa music. Whether you're a seasoned dancer or taking your first steps onto the dance floor, our event welcomes everyone to sway, twirl, and connect in a judgment-free zone. Feel the vibrant energy as you move to the sultry rhythms, forging connections and creating memories that dance beyond the ordinary. Embrace the joy of expression, celebrate love in motion, and let the music guide you in an inclusive space where every spin and dip reflects the beauty of unity and acceptance. Join us for a night of spirited salsa, camaraderie, and the sheer delight of dancing your authentic self.",

				organiserId: 2,
				online_link: null,
				latitude: 41.3811192,
				longitude: 2.1806109,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Volleyball Afternoon",
				description:
					"Escape to the sun-kissed shores for a day of sun, sand, and sports with our Beach Volleyball and Picnic event. Picture a pristine beach setting, where the rhythmic sound of waves serves as the backdrop to an exhilarating game of volleyball. Feel the warm sand beneath your feet as you dive, spike, and set against the stunning coastal panorama. After an energetic match, unwind with a leisurely picnic on the beach, where delicious treats and refreshing beverages await. Lounge in the shade of a beach umbrella, share laughter with friends, and soak in the vibrant atmosphere of camaraderie. Join us for a perfect blend of sport and relaxation, creating lasting memories of a day filled with beachside fun, delicious bites, and the joyful spirit of summer.",

				organiserId: 2,
				online_link: null,
				latitude: 41.3811192,
				longitude: 2.1806109,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 0,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 0,
				name: "Craft Night",
				description:
					"Unleash your creativity and join us for a magical Craft Night where artistic expression knows no bounds. Picture a cozy atmosphere filled with vibrant colors, laughter, and the hum of imagination at work. Gather with fellow craft enthusiasts to explore a myriad of artistic possibilities – from painting and sculpting to DIY projects and beyond. With a palette of materials at your fingertips, let your creativity flow as you bring your ideas to life. Whether you're a seasoned crafter or just discovering your artistic flair, Craft Night is a space for self-expression and community. Share tips, swap stories, and revel in the joy of creating something uniquely yours. Join us for an evening of crafty delights, where every masterpiece is a testament to the boundless beauty of imagination.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162504,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 1,
				start_time: "2024-01-0721:00:00",
				end_time: "2024-01-07T00:00:00",
				is_group: 1,
				name: "Salsa Night",
				description:
					"Step into the enchanting world of melody and rhythm at our Music Night, where the air is filled with the soulful notes of live performances and the shared joy of musical appreciation. Immerse yourself in a diverse tapestry of genres, from acoustic serenades to upbeat tunes that make you want to dance. Our talented musicians will transport you through an evening of musical enchantment, creating an atmosphere that resonates with harmony and emotion. Whether you're a connoisseur of classical compositions or a lover of modern beats, Music Night is a celebration of the universal language that connects us all. Join us for an unforgettable night where melodies weave stories and every note carries the promise of shared experiences and cherished memories.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162504,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 0,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 0,
				name: "Hike in the Mountains",
				description:
					"Embark on an invigorating journey into the heart of nature with our Mountain Hike adventure. Picture crisp, clean air, panoramic vistas, and the thrill of conquering rugged trails that lead to breathtaking summits. As you ascend, immerse yourself in the serene beauty of towering trees, alpine meadows, and the occasional glimpse of wildlife. Feel the crunch of gravel beneath your hiking boots and relish the tranquility that surrounds you. Our expert guides will lead you through winding paths, sharing insights about the flora and fauna that call the mountains home. At the peak, savor a well-deserved moment of triumph, as panoramic views stretch before you like a magnificent tapestry. Join us for a mountain hike — an experience that not only challenges your physical limits but also rejuvenates your spirit in the embrace of untamed wilderness.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162553,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Hat Making",
				description:
					"Embark on a creative journey into the world of fashion with our Hat Making Workshop. Imagine a vibrant space filled with an array of materials, colors, and the excitement of crafting your own stylish headwear. Led by skilled artisans, this hands-on experience invites you to explore the art of hat making, from selecting fabrics and embellishments to shaping and customizing your unique design. Unleash your imagination as you experiment with different styles, whether it's a chic sun hat, a trendy fascinator, or a classic fedora. This workshop is perfect for all skill levels, fostering an atmosphere of camaraderie and self-expression. Join us for a day of creative exploration, where every stitch and detail reflects your personal style, making your hat not just an accessory, but a wearable work of art.",

				organiserId: 2,
				online_link: null,
				latitude: 41.930299,
				longitude: 2.254504,
				city: "Vic",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Queers for Climate",
				description:
					"Join us for an empowering gathering at our Queers for Climate Meeting, where passion for environmental justice meets the strength of community. Picture an inclusive space where diverse voices come together to address the urgent challenges posed by climate change. Engage in meaningful discussions, share insights, and explore how our unique perspectives as members of the LGBTQ community can contribute to sustainable solutions. From collaborative initiatives to individual actions, we'll delve into the intersectionality of queerness and climate advocacy. Together, we strive to create a world that embraces both equality and environmental stewardship. Join Queers for Climate in fostering a sense of unity, purpose, and collective responsibility as we work towards a greener and more inclusive future for all.",

				organiserId: 2,
				online_link: null,
				latitude: 41.425564,
				longitude: 2.222402,
				city: "Sant Adrià del Besós",
				createdAt: new Date(),
				updatedAt: new Date(),
			},

			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-01T12:00:00",
				end_time: "2024-01-01T17:00:00",
				is_group: 1,
				name: "Beach BBQ",
				description:
					"Join us for a sizzling day of flavor and fun at our BBQ in the Park event! Picture a sun-drenched day filled with the mouthwatering aroma of grilled delights wafting through the air. Bring your friends and family to indulge in a feast of smoky barbecue favorites, from perfectly grilled burgers and hot dogs to tender ribs and savory skewers. The park transforms into a lively hub of laughter, games, and good times. Enjoy the laid-back atmosphere as you lounge on picnic blankets, savoring delicious bites and refreshing drinks. With live music, friendly faces, and the great outdoors as your backdrop, our BBQ in the Park promises a perfect blend of relaxation and gastronomic delight. Come join the festivities and make lasting memories in the heart of nature!",

				organiserId: 2,
				online_link: null,
				latitude: 41.399546,
				longitude: 2.170494,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 1,
				start_time: "2024-01-05T20:00:00",
				end_time: "2024-01-05T23:30:00",
				is_group: 1,
				name: "Outdoor Cinema",
				description:
					"Experience the warmth and inspiration of a heartfelt movie night with 'Pride.' This cinematic gem invites you on a captivating journey, exploring the triumphs and challenges of a diverse group coming together for a common cause. As the characters navigate through the intricacies of unity, acceptance, and the pursuit of equality, 'Pride' weaves a powerful narrative that transcends boundaries. Join us for an evening of laughter, tears, and a celebration of love and solidarity as we immerse ourselves in the beauty of 'Pride,' a film that not only entertains but leaves an indelible mark on the heart.",
				organiserId: 2,
				online_link: " https://zoom.us/j/5551112222",
				latitude: 41.401459,
				longitude: 2.17656,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 0,
				start_time: null,
				end_time: null,
				is_group: 0,
				name: "Read this article!",
				description:
					"Embark on a journey of insight and discovery as you dive into an enriching article about the acclaimed film 'Pride.' This compelling piece unravels the layers of the movie, offering a thoughtful exploration of its themes, characters, and the profound impact it has left on audiences. Immerse yourself in the analysis, gaining a deeper understanding of the film's narrative nuances, social relevance, and the powerful emotions it elicits. Delve into interviews with the cast and creators, uncovering the behind-the-scenes magic that brought this cinematic gem to life. Whether you're a film enthusiast or simply intrigued by powerful storytelling, reading this article is a gateway to appreciating the artistry and cultural significance of 'Pride.' Join us on this intellectual journey as we celebrate the beauty of storytelling and the profound messages embedded in this remarkable film.",

				organiserId: 1,
				online_link:
					"https://www.theguardian.com/film/2014/aug/31/pride-film-gay-activists-miners-strike-interview",
				latitude: 41.401173,
				longitude: 2.172362,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: null,
				end_time: null,
				is_group: 0,
				name: "Support this store!",
				description:
					"Step into a world of literary diversity and support a vibrant community by purchasing a book from our local LGBTQ bookstore. As you browse the shelves, each book becomes a doorway to unique narratives, diverse voices, and untold stories that celebrate the richness of the LGBTQ experience. Your purchase not only adds a new gem to your personal library but also contributes directly to fostering inclusivity and empowering a local business that champions diversity. Join us in promoting a love for literature and supporting our LGBTQ community as we cherish the joy of discovery, one book at a time. Your choice makes a difference, creating a more inclusive and welcoming space for everyone in our shared literary journey.",

				organiserId: 1,
				online_link: null,
				latitude: 41.403217,
				longitude: 2.17056,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-06T18:00:00",
				end_time: "2024-01-06T20:30:00",
				is_group: 1,
				name: "Date night!",
				description:
					"Embark on a thrilling journey of connection and possibility with our speed dating event! Imagine a vibrant atmosphere filled with laughter, anticipation, and the promise of exciting encounters. Whether you're seeking romance or simply eager to expand your social circle, speed dating offers a dynamic and efficient way to meet like-minded individuals. Engage in a series of brief, meaningful conversations, each lasting just long enough to make a memorable impression. With a timer ticking, discover the chemistry that sparks genuine connections and opens the door to potential relationships. Join us for an evening of spontaneity and discovery, where every conversation is a chance to find a new connection and perhaps even a spark that lasts a lifetime. Get ready to embrace the thrill of meeting new faces and exploring the endless possibilities that speed dating brings to the world of relationships.",
				organiserId: 2,
				online_link: null,
				latitude: 41.402914,
				longitude: 2.17466,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Forest Walk",
				description:
					"Escape the hustle and bustle of daily life with a leisurely park walk that promises a breath of fresh air and a rejuvenating experience. As you enter the green oasis, the rhythmic rustle of leaves overhead and the gentle melodies of nature surround you. Meander along winding paths, each turn revealing picturesque scenes of blooming flowers, towering trees, and tranquil ponds. Embrace the serenity as you stroll under the canopy of branches, sunlight filtering through the leaves. Take a moment to pause at scenic viewpoints, allowing the beauty of your surroundings to sink in. Whether you're seeking solitude for introspection or sharing the joy with companions, a park walk is an opportunity to connect with nature, clear your mind, and find solace in the simple yet profound wonders of the outdoors.",
				organiserId: 2,
				online_link: null,
				latitude: 41.403243,
				longitude: 2.168971,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Debate on the Far Right",
				description:
					"Engage in a thought-provoking and challenging exploration of political ideologies with a neo-fascism debate. This discourse invites participants to critically examine the principles and tenets associated with neo-fascist thought. Delve into the complexities of historical context, social implications, and the contemporary resonance of these ideologies. As participants present and counter arguments, the debate fosters an environment for rigorous intellectual exchange, aiming to deepen understanding and provoke critical thinking. While discussions on such topics can be intense, the goal is to provide a platform for examining contrasting viewpoints within the bounds of respectful discourse. Join us for an enlightening and intellectually stimulating neo-fascism debate that encourages reflection and promotes a nuanced understanding of political ideologies in today's world.",
				organiserId: 2,
				online_link: null,
				latitude: 41.572815,
				longitude: 2.016293,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Debate Club",
				description:
					"Step into a vibrant world of literature and lively discourse with our LGBTQ Book Club and Debate. Immerse yourself in a diverse selection of books that beautifully capture the LGBTQ experience, exploring themes of love, identity, and resilience. Engage in thought-provoking discussions that celebrate the rich tapestry of LGBTQ narratives, fostering a sense of community and understanding. Our book club not only provides a space for shared literary exploration but also encourages spirited debates that delve into the complexities of the stories we read. Join us in creating an inclusive and supportive environment where diverse voices are heard, stories are cherished, and where every meeting is an opportunity to learn, connect, and celebrate the vibrant LGBTQ literary landscape.",

				organiserId: 2,
				online_link: null,
				latitude: 41.572815,
				longitude: 2.016293,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},

			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Bachata Night",
				description:
					"Dive into the rhythm of diversity and inclusion with our LGBTQ Salsa Dancing Night. Join a community that celebrates the freedom of self-expression through the lively and passionate beats of salsa music. Whether you're a seasoned dancer or taking your first steps onto the dance floor, our event welcomes everyone to sway, twirl, and connect in a judgment-free zone. Feel the vibrant energy as you move to the sultry rhythms, forging connections and creating memories that dance beyond the ordinary. Embrace the joy of expression, celebrate love in motion, and let the music guide you in an inclusive space where every spin and dip reflects the beauty of unity and acceptance. Join us for a night of spirited salsa, camaraderie, and the sheer delight of dancing your authentic self.",

				organiserId: 2,
				online_link: null,
				latitude: 41.3811192,
				longitude: 2.1806109,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Badminton Tournamet",
				description:
					"Escape to the sun-kissed shores for a day of sun, sand, and sports with our Beach Volleyball and Picnic event. Picture a pristine beach setting, where the rhythmic sound of waves serves as the backdrop to an exhilarating game of volleyball. Feel the warm sand beneath your feet as you dive, spike, and set against the stunning coastal panorama. After an energetic match, unwind with a leisurely picnic on the beach, where delicious treats and refreshing beverages await. Lounge in the shade of a beach umbrella, share laughter with friends, and soak in the vibrant atmosphere of camaraderie. Join us for a perfect blend of sport and relaxation, creating lasting memories of a day filled with beachside fun, delicious bites, and the joyful spirit of summer.",

				organiserId: 2,
				online_link: null,
				latitude: 41.3811192,
				longitude: 2.1806109,
				city: "Terrassa",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Arts Night",
				description:
					"Unleash your creativity and join us for a magical Craft Night where artistic expression knows no bounds. Picture a cozy atmosphere filled with vibrant colors, laughter, and the hum of imagination at work. Gather with fellow craft enthusiasts to explore a myriad of artistic possibilities – from painting and sculpting to DIY projects and beyond. With a palette of materials at your fingertips, let your creativity flow as you bring your ideas to life. Whether you're a seasoned crafter or just discovering your artistic flair, Craft Night is a space for self-expression and community. Share tips, swap stories, and revel in the joy of creating something uniquely yours. Join us for an evening of crafty delights, where every masterpiece is a testament to the boundless beauty of imagination.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162504,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 1,
				start_time: "2024-01-0721:00:00",
				end_time: "2024-01-07T00:00:00",
				is_group: 1,
				name: "Music Night",
				description:
					"Step into the enchanting world of melody and rhythm at our Music Night, where the air is filled with the soulful notes of live performances and the shared joy of musical appreciation. Immerse yourself in a diverse tapestry of genres, from acoustic serenades to upbeat tunes that make you want to dance. Our talented musicians will transport you through an evening of musical enchantment, creating an atmosphere that resonates with harmony and emotion. Whether you're a connoisseur of classical compositions or a lover of modern beats, Music Night is a celebration of the universal language that connects us all. Join us for an unforgettable night where melodies weave stories and every note carries the promise of shared experiences and cherished memories.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162504,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 1,
				in_person: 0,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 0,
				name: "Hike by the Sea",
				description:
					"Embark on an invigorating journey into the heart of nature with our Mountain Hike adventure. Picture crisp, clean air, panoramic vistas, and the thrill of conquering rugged trails that lead to breathtaking summits. As you ascend, immerse yourself in the serene beauty of towering trees, alpine meadows, and the occasional glimpse of wildlife. Feel the crunch of gravel beneath your hiking boots and relish the tranquility that surrounds you. Our expert guides will lead you through winding paths, sharing insights about the flora and fauna that call the mountains home. At the peak, savor a well-deserved moment of triumph, as panoramic views stretch before you like a magnificent tapestry. Join us for a mountain hike — an experience that not only challenges your physical limits but also rejuvenates your spirit in the embrace of untamed wilderness.",
				organiserId: 2,
				online_link: null,
				latitude: 41.405061,
				longitude: 2.162553,
				city: "Barcelona",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Scarf Making",
				description:
					"Embark on a creative journey into the world of fashion with our Hat Making Workshop. Imagine a vibrant space filled with an array of materials, colors, and the excitement of crafting your own stylish headwear. Led by skilled artisans, this hands-on experience invites you to explore the art of hat making, from selecting fabrics and embellishments to shaping and customizing your unique design. Unleash your imagination as you experiment with different styles, whether it's a chic sun hat, a trendy fascinator, or a classic fedora. This workshop is perfect for all skill levels, fostering an atmosphere of camaraderie and self-expression. Join us for a day of creative exploration, where every stitch and detail reflects your personal style, making your hat not just an accessory, but a wearable work of art.",

				organiserId: 2,
				online_link: null,
				latitude: 41.930299,
				longitude: 2.254504,
				city: "Vic",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
			{
				online: 0,
				in_person: 1,
				start_time: "2024-01-07T13:00:00",
				end_time: "2024-01-07T16:00:00",
				is_group: 1,
				name: "Queers for Climate",
				description:
					"Join us for an empowering gathering at our Queers for Climate Meeting, where passion for environmental justice meets the strength of community. Picture an inclusive space where diverse voices come together to address the urgent challenges posed by climate change. Engage in meaningful discussions, share insights, and explore how our unique perspectives as members of the LGBTQ community can contribute to sustainable solutions. From collaborative initiatives to individual actions, we'll delve into the intersectionality of queerness and climate advocacy. Together, we strive to create a world that embraces both equality and environmental stewardship. Join Queers for Climate in fostering a sense of unity, purpose, and collective responsibility as we work towards a greener and more inclusive future for all.",

				organiserId: 2,
				online_link: null,
				latitude: 41.425564,
				longitude: 2.222402,
				city: "Sant Adrià del Besós",
				createdAt: new Date(),
				updatedAt: new Date(),
			},
		]);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete("Actions", null, {});
	},
};
